[package]
name = "ctrlhome"
version = "0.0.1"
authors = [ "Raimundo Martins <raimundoomartins@gmail.com>" ]

[dependencies]
encoding = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
error-chain = "*"
