[package]
name = "ctrlhome"
version = "0.0.1"
authors = [ "Raimundo Martins <raimundoomartins@gmail.com>" ]

[dependencies]
encoding = "0.2"
serde = "1"
serde_derive = "1"
serde_json = "1"
error-chain = "0.11"
